export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const INCREMENT_SCORE = "INCREMENT_SCORE";
export const MOVE_TO_NEXT_QUESTION = "MOVE_TO_NEXT_QUESTION";